### ISSUE TITLE
Minor bugs and issues

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#147]
Various minor builder related issues. These can be resolved in separate PRs, or all together.

### Tasks
- [x] Pressing enter when searching in a multiselect should choose the option with the best match. It should be indicated with a very light highlight (e.g. `background-color: $blue-100`).
- [x] Pressing escape when a style is selected should cancel the edit
- [x] If a style editing session ends and there's a style with empty property and value, remove it
- [ ] <strike>If the site is empty and the root is not selected, clicking the editor should select the root.</strike>
- [ ] Copy/paste style should include child/override styles
