### ISSUE TITLE
Improve Prosemirror links

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#310]
Add some quality of life improvements to link tooltips. Since both Word and Google docs use cmd/ctrl+k as the link hotkey, we can use it too for familiarity.

### tasks
- [x] Include a "remove" icon button that clears the link
- [x] Add a separate input for modifying the link text, currently it's inconvenient to edit in the link text.
- [x] Add a hotkey (cmd/ctrl+k) that converts a prosemirror selection to a link
- [x] Link hotkey should remove the link from the portion of a selection
