### ISSUE TITLE
Move style toolbar items to component menu

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#335]
Move the remaining style toolbar items that affect style to the component menu.

### Tasks
- [ ] Move layout/container options to a section in the component menu
- [ ] Move text options to a section in the component menu
- [ ] Rename StyleToolbar to SiteToolbar

### Notes

This is to make space for version/publish info and buttons.
