### ISSUE TITLE
Add create-draft endpoint

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#349]
Add endpoint `/sites/:site_id/actions/create_draft` that creates a draft site version if one doesn't exist. If a draft already exists, do nothing.

### Tasks
- [x] Add endpoint `/sites/:site_id/actions/create_draft`
- [x] Create a draft if one doesn't exist. A draft exists if there is more than one site version, and the latest site version has `published: false`
- [x] Return the same output as list-site-versions
- [x] Add integration tests
