### ISSUE TITLE
Code editor improvements

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#472]
Improve the behavior/global style code editors.

### Tasks
- [ ] Tab should create 4 spaces
- [ ] Enter goes to correct indentation
- [ ] Highlight helper variables
- [ ] Auto-format?
- TBD
