### ISSUE TITLE
Show editor events in component menu

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#485]
Show editor events in the component menu, and allow users to modify their behaviors.

### Tasks
- [x] Show editor events at bottom of component menu
- [x] Split builtin editor behaviors and normal behaviors
- [x] Dynamically build `editor.editorEvents` on deserialize, skip in live/preview mode
