### ISSUE TITLE
Editor UX improvements 240614

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#489]
#### Tasks

- [x] Require “/“ in page route
- [x] Automatically focus name input on new page
- [x] Focus name in new behavior (modal)
- [x] Can’t drop into empty root
- [x] Whitelist some html props for editor display 
- [x] Fix image component dragImage
- [x] Drag width/height of component not scaled by builderScale
- [x] Set img src/background-url by dropping asset
