### ISSUE TITLE
Reload site on tab change

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#567]
It's more efficient to reduce polling frequency on the preview page, but reload as soon as the tab is focused. Along with #412, this should make the preview updates appear more seamless. Reloading when the editor tab is focused may also help reduce conflicts when the site is open in multiple tabs.

### Tasks
- [x] Reload site in editor when tab focused
- [x] Reload site in preview when tab focused
- [x] Reduce polling frequency
- <strike>Consider a slider in site options for adjusting preview reload frequency</strike>
