### ISSUE TITLE
Prosemirror improvements and fixes

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#607]
### Tasks
- [ ] Add global styling for prosemirror (link, underline, etc).
- [ ] Prosemirror text reflows when clicked due to padding added by the editor. Remove it or only including when the text is a single line.
- [ ] Strip outer div when content is a single line/no nested divs
- [ ] Fix strange behavior due to prosemirror divs in link/span/etc (may be fixed by previous task)
